### ISSUE TITLE
Cookie import

### ISSUE THREAD

**Issue by binaar** [Audiens/adform-client#3]
First, thanks for great repository!

It would be perfect if there would be Cookie import endpoint as well. Is there any plans to add it?

I'm stuck with implementing this:
https://dmp.adform.com/Help/Api/POST-v1-dataproviders-dataProviderId-cookies

**Comment by ranpafin** [comment]
Hello @binaar  thanks for the appreciations.

We're not planning to implement this endpoint in the near future as we're still using the S3 .csv upload provided by Adform. 

In any case we'll gladly accept any PR that cover this functionality :smile:  Especially considering the API endpoint provides **way more** control over the upload.

**Comment by karonte691** [comment]
Hi @binaar

I'm working on an implementation of the AdForm Cookie api. You can take a look on on the branch https://github.com/Audiens/adform-client/tree/CookieProvider . It's not fully tested yet and not sure when it will be ready for a stable release, but you can give a look, maybe there is the solution for your problem.

**Comment by binaar** [comment]
Hi @karonte691 !

Awesome there seems to be some bugs for me, but thats perfect place to build from!

Thanks!
